### ISSUE TITLE
change so that the to-pdf action only runs when a md is pushed

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/ITGC-field-doc#2]
Once the md to pdf action is running as required, the top of the yml file should be changed from 
```
on: [push]
```
to
```
on:
  push:
    paths:
    - '**.md'
```
so that it only runs when a markdown file is pushed.
